name: Resume CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'resume-ch' # TODO: update Google Cloud project id

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [19.6]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - uses: actions/upload-artifact@v3
        with:
          name: webpack artifacts
          path: build/
        
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
      
    name: Deploy app to GCS
    needs: build
    runs-on: ubuntu-latest      
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Download build artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: webpack artifacts
          path: build
          
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}  
        
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com
          
      - id: upload-files
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: ${{steps.download.outputs.download-path}} 
          destination: 'vinitha.info'
          parent: false
